[build-system]
requires = ["setuptools>=75.4"]
build-backend = "setuptools.build_meta"


[project]
name = "doxy-sip"
description = "A Sphinx extension for semi-automatic class documentation from SIP bindings and Doxygen"
readme = "README.rst"
license = "BSD-3-Clause"
license-files = ["LICENSE"]
requires-python = ">=3.9"
dependencies = ["sphinx>=7.2", "sip>=6.13"]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Framework :: Sphinx :: Extension",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Topic :: Documentation :: Sphinx",
    "Topic :: Software Development :: Documentation",
]
urls.homepage = "https://github.com/clesav/doxy-sip"

version = "0.0.1"


[[project.authors]]
name = "C. Savergne"
email = "csavergne@yahoo.com"

